### ISSUE TITLE
Space not found on gitbook.com

### ISSUE THREAD

**Issue by albohlabs** [fission-suite/haskell-for-typescript-devs#3]
The link to app.gitbook.com leads to "Space not found".

Btw, thanks for this awesome guide.

**Comment by bmann** [comment]
@albohlabs thank you! Fixed the link https://runfission.gitbook.io/haskell-for-typescript-devs/

We'll probably move this to its own domain so it can be a bit more portable.

**Comment by expede** [comment]
Glad that you're enjoying the guide 🙌🎉😁
